name: inert
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  form_field_validator: ^1.1.0
  google_nav_bar: ^5.0.3
  line_icons: ^2.0.1
  carousel_slider: ^3.0.0
  sleek_circular_slider: ^2.0.0
  change_app_package_name: ^1.0.0
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  modal_progress_hud: ^0.1.3
  firebase_storage: ^8.1.0
  image_picker: ^0.7.5+2
  camera: ^0.8.1
  path_provider: ^2.0.1
  image_gallery: ^1.2.0
  photo_manager: ^1.2.0
  like_button: ^2.0.2
  auto_size_text: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: "launcher_icon"
  image_path: "icon/mainlogo.png"


flutter:
  uses-material-design: true
  fonts :
    - family: Comforta
      fonts :
        - asset: fonts/comforta.ttf
  assets:
    - images/back.jpg
    - images/1st.png
    - images/2nd.jpg
    - images/2nd.png
    - images/3rd.jpg
    - images/4th.jpg
    - images/pf1.png
    - images/pf2.png
    - images/pf3.png
    - images/mainlogo.png
    - images/background.jpg
